rules = [
  OrganizeImports,
  RemoveUnused,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  ProcedureSyntax
]

OrganizeImports {
  groupedImports = Merge
  groups = [
    "re:javax?\\.",
    "scala.",
    "*"
  ]
  removeUnused = false  // -Wunused:all already covers this; RemoveUnused is the rewriter
  targetDialect = Scala3
}
